steps:
  docker_build:
    image: docker:27-cli
    commands:
      - docker build . --file Dockerfile --tag test-image:${CI_COMMIT_SHA}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
